name: "schemachange cicd"

on:
  push:
    branches:
      - main

jobs:
    deploy-snowflake-change-job:
      runs-on: ubuntu-latest

      steps:
        - name: checkout repository
          uses: actions/checkout@v3

        - name: Use Python 3.8.x
          uses: actions/setup-python@v2.2.1
          with:
              python-version: 3.8.x

        - name: 'run schema change'
          env:
            SNOWFLAKE_ACCOUNT: ${{secrets.SF_ACCOUNT}}
            SNOWFLAKE_USERNAME: ${{secrets.SF_USER}}
            SNOWFLAKE_PASSWORD: ${{secrets.SNOWFLAKE_PASSWORD}}
            SNOWFLAKE_WAREHOUSE: ${{secrets.SF_WAREHOUSE}}
            SNOWFLAKE_ROLE: ${{secrets.SF_ROLE}}
            SNOWFLAKE_DATABASE: ${{secrets.SF_DB}}

          run: |
            echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
            python --version
            echo "step 1 : installing schema change"
            pip install -r requirements.txt
            
            echo "step2 : Running schemachange"
            echo "SF_PASSWORD : $SNOWFLAKE_PASSWORD"
            schemachange -f $GITHUB_WORKSPACE/snowflake_config -a $SNOWFLAKE_ACCOUNT -u $SNOWFLAKE_USERNAME -r $SNOWFLAKE_ROLE -w $SNOWFLAKE_WAREHOUSE -d $SNOWFLAKE_DATABASE --create-change-history-table
